package com.agilecheckup.persistency.entity.base;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;

import java.io.Serializable;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@DynamoDBDocument
public class BaseEntity implements Identifiable, Serializable {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  @Builder.Default
  private String id = UUID.randomUUID().toString();
}